server:
  port: 8080

spring:
  application:
    name: bank-cards-api
  
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards?sslmode=disable&connectTimeout=10
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  liquibase:
    enabled: true
    change-log: classpath:db/migration/db.changelog-master.yaml

jwt:
  secret: MySuperSecretKeyForJWT2026BankCardsProjectMustBeLongEnough!
  expiration: 86400000
  refresh-expiration: 604800000

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.example.bankcards: DEBUG
    org.springframework.security: DEBUG
